#!/bin/sh
# Copyright (C) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# SPDX-License-Identifier: MIT

if [ "$(uname)" = "Darwin" ]; then
    SO=dylib
else
    SO=so
fi

# find libtsano
CURDIR=$(pwd)
PREFIX=$(readlink -f $(pwd)/..)

if [ -f "$PREFIX/libtsano.$SO" ]; then
    LIBTSANO="$PREFIX/libtsano.$SO"
elif [ -f "$CURDIR/build/libtsano.$SO" ]; then
    LIBTSANO="$CURDIR/build/libtsano.$SO"
else
    echo "could not find libtsano.$SO"
    exit 1
fi

# prepare temporary library path
TSANO_DIR=/tmp/tsano
mkdir -p $TSANO_DIR

# symlink tsano to possible tsan libraries
(
    cd "$TSANO_DIR"
    if [ ! -f libtsan.$SO.0 ]; then
        ln -s $LIBTSANO libtsan.$SO.0
    fi
    if [ ! -f libtsan.$SO.1 ]; then
        ln -s $LIBTSANO libtsan.$SO.1
    fi
    if [ ! -f libtsan.$SO.2 ]; then
        ln -s $LIBTSANO libtsan.$SO.2
    fi
    if [ $SO = "dylib" ]; then
        if [ ! -f libclang_rt.tsan_osx_dynamic.dylib ]; then
            ln -s $LIBTSANO libclang_rt.tsan_osx_dynamic.dylib
        fi
    fi
    if [ ! -f libclang_rt.tsan-x86_64.$SO ]; then
        ln -s $LIBTSANO libclang_rt.tsan-x86_64.$SO
    fi
)

# prepare LD_LIBRARY_PATH
LDPATH="$TSANO_DIR"
if [ -z "$LD_LIBRARY_PATH" ]; then
    LDPATH="$TSANO_DIR:$LD_LIBRARY_PATH"
fi

# execute command
exec env LD_LIBRARY_PATH=$LDPATH $@
