#!/bin/sh

SO=so
if [ "$(uname)" = "Darwin" ]; then
    SO=dylib
    DYLD=yes
fi

SCRIPT_DIR=$(dirname $(readlink -f $0))
# if not installed, fall back to repo/build prefix
BINGO_PREFIX="/usr/local"
if [ ! -d "$BINGO_PREFIX/lib/bingo" ]; then
    BINGO_PREFIX=$(readlink -f $SCRIPT_DIR/../build)
    MOD_DIR=$BINGO_PREFIX/mod
else
    MOD_DIR=$BINGO_PREFIX/lib/bingo
fi
#echo "BINGO: $BINGO_PREFIX"

PRELOAD="$BINGO_PREFIX/lib/libbingo-builtin.$SO"
args=""
while [ "$#" != "0" ]; do
    case "$1" in
        *)
            args="${args} $1"
        ;;
    esac
    shift
done

exec $SCRIPT_DIR/tsano env LD_PRELOAD=$PRELOAD $args
