#!/bin/sh
# Copyright (C) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# SPDX-License-Identifier: MIT

if [ "$(uname)" = "Darwin" ]; then
    SO=dylib
else
    SO=so
fi

# find libdice
PARDIR=$(readlink -f $(dirname "$0")/..)
LIBDIR=$(readlink -f "$PARDIR")/lib

if [ -f "$LIBDIR/libdice.$SO" ]; then
    LIBDICE="$LIBDIR/libdice.$SO"
    DICE_DIR="$LIBDIR/dice"
    TSANO=$(which tsano)
elif [ -f "$PARDIR/build/src/dice/libdice.$SO" ]; then
    LIBDICE="$PARDIR/build/src/dice/libdice.$SO"
    DICE_DIR="$PARDIR/build/src/mod"
    TSANO="$PARDIR/deps/tsano/tsano"
    TSANO_LIBDIR="$PARDIR/build/deps/tsano"
else
    echo "could not find libdice.$SO"
    exit 1
fi

if [ ! -f "$TSANO" ]; then
    echo "could not find tsano"
    exit 1
fi

# prepare preload
PRELOAD=""
args=""
while [ "$#" != "0" ]; do
    case "$1" in
        -self)
            PRELOAD="$PRELOAD:$DICE_DIR/mod-self.$SO"
        ;;
        -tsan)
            PRELOAD="$PRELOAD:$DICE_DIR/mod-tsan.$SO"
            PRELOAD="$PRELOAD:$DICE_DIR/mod-stacktrace.$SO"
        ;;
        -pthread)
            PRELOAD="$PRELOAD:$DICE_DIR/mod-pthread_create.$SO"
            PRELOAD="$PRELOAD:$DICE_DIR/mod-pthread_mutex.$SO"
            PRELOAD="$PRELOAD:$DICE_DIR/mod-pthread_cond.$SO"
            PRELOAD="$PRELOAD:$DICE_DIR/mod-pthread_rwlock.$SO"
        ;;
        -autocept)
            PRELOAD="$PRELOAD:$DICE_DIR/mod-autocept.$SO"
        ;;
        -with)
            shift
            LIBDICE="$1"
        ;;
        *)
            args="${args} $1"
        ;;
    esac
    shift
done

# prepend libdice
PRELOAD="$LIBDICE$PRELOAD"

# prefix tsano's libdir if necessary
TSANO="env TSANO_LIBDIR=$TSANO_LIBDIR $TSANO"

# execute command
if [ $SO = "dylib" ]; then
    exec $TSANO env DYLD_INSERT_LIBRARIES=$PRELOAD $args
else
    exec $TSANO env LD_PRELOAD=$PRELOAD $args
fi
