#!/bin/sh

SO=so
if [ "$(uname)" = "Darwin" ]; then
    SO=dylib
    DYLD=yes
fi

SCRIPT_DIR=$(dirname $(readlink -f $0))
# if not installed, fall back to repo/build prefix
DICE_PREFIX="/usr/local"
if [ ! -d "$DICE_PREFIX/lib/dice" ]; then
    DICE_PREFIX=$(readlink -f $SCRIPT_DIR/../build)
    MOD_DIR=$DICE_PREFIX/mod
else
    MOD_DIR=$DICE_PREFIX/lib/dice
fi
#echo "DICE: $DICE_PREFIX"

PRELOAD="$DICE_PREFIX/lib/libdice-builtin.$SO"
args=""
while [ "$#" != "0" ]; do
    case "$1" in
        *)
            args="${args} $1"
        ;;
    esac
    shift
done

exec $SCRIPT_DIR/tsano env LD_PRELOAD=$PRELOAD $args
